// Code generated by ent, DO NOT EDIT.

package reaction

import (
	"time"
)

const (
	// Label holds the string label denoting the reaction type in the database.
	Label = "reaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTemplate holds the string denoting the template edge name in mutations.
	EdgeTemplate = "template"
	// EdgePoll holds the string denoting the poll edge name in mutations.
	EdgePoll = "poll"
	// Table holds the table name of the reaction in the database.
	Table = "reactions"
	// TemplateTable is the table that holds the template relation/edge.
	TemplateTable = "reactions"
	// TemplateInverseTable is the table name for the ReactionTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "reactiontemplate" package.
	TemplateInverseTable = "reaction_templates"
	// TemplateColumn is the table column denoting the template relation/edge.
	TemplateColumn = "reaction_template"
	// PollTable is the table that holds the poll relation/edge.
	PollTable = "reactions"
	// PollInverseTable is the table name for the Poll entity.
	// It exists in this package in order to avoid circular dependency with the "poll" package.
	PollInverseTable = "polls"
	// PollColumn is the table column denoting the poll relation/edge.
	PollColumn = "poll_reactions"
)

// Columns holds all SQL columns for reaction fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "reactions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"poll_reactions",
	"reaction_template",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
