// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Poll is the predicate function for poll builders.
type Poll func(*sql.Selector)

// Reaction is the predicate function for reaction builders.
type Reaction func(*sql.Selector)

// ReactionTemplate is the predicate function for reactiontemplate builders.
type ReactionTemplate func(*sql.Selector)

// Vote is the predicate function for vote builders.
type Vote func(*sql.Selector)

// VoteTemplate is the predicate function for votetemplate builders.
type VoteTemplate func(*sql.Selector)
