// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/poll"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/reaction"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/reactiontemplate"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/schema"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/vote"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/votetemplate"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pollMixin := schema.Poll{}.Mixin()
	pollMixinFields0 := pollMixin[0].Fields()
	_ = pollMixinFields0
	pollMixinFields1 := pollMixin[1].Fields()
	_ = pollMixinFields1
	pollFields := schema.Poll{}.Fields()
	_ = pollFields
	// pollDescCreatedAt is the schema descriptor for created_at field.
	pollDescCreatedAt := pollMixinFields0[0].Descriptor()
	// poll.DefaultCreatedAt holds the default value on creation for the created_at field.
	poll.DefaultCreatedAt = pollDescCreatedAt.Default.(func() time.Time)
	// pollDescUpdatedAt is the schema descriptor for updated_at field.
	pollDescUpdatedAt := pollMixinFields0[1].Descriptor()
	// poll.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	poll.DefaultUpdatedAt = pollDescUpdatedAt.Default.(func() time.Time)
	// poll.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	poll.UpdateDefaultUpdatedAt = pollDescUpdatedAt.UpdateDefault.(func() time.Time)
	// pollDescIsDeleted is the schema descriptor for is_deleted field.
	pollDescIsDeleted := pollMixinFields1[0].Descriptor()
	// poll.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	poll.DefaultIsDeleted = pollDescIsDeleted.Default.(bool)
	// pollDescTitle is the schema descriptor for title field.
	pollDescTitle := pollFields[0].Descriptor()
	// poll.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	poll.TitleValidator = pollDescTitle.Validators[0].(func(string) error)
	// pollDescIsLive is the schema descriptor for is_live field.
	pollDescIsLive := pollFields[2].Descriptor()
	// poll.DefaultIsLive holds the default value on creation for the is_live field.
	poll.DefaultIsLive = pollDescIsLive.Default.(bool)
	// pollDescCanVote is the schema descriptor for can_vote field.
	pollDescCanVote := pollFields[3].Descriptor()
	// poll.DefaultCanVote holds the default value on creation for the can_vote field.
	poll.DefaultCanVote = pollDescCanVote.Default.(bool)
	// pollDescCanReact is the schema descriptor for can_react field.
	pollDescCanReact := pollFields[4].Descriptor()
	// poll.DefaultCanReact holds the default value on creation for the can_react field.
	poll.DefaultCanReact = pollDescCanReact.Default.(bool)
	// pollDescCanSeeResults is the schema descriptor for can_see_results field.
	pollDescCanSeeResults := pollFields[5].Descriptor()
	// poll.DefaultCanSeeResults holds the default value on creation for the can_see_results field.
	poll.DefaultCanSeeResults = pollDescCanSeeResults.Default.(bool)
	reactionMixin := schema.Reaction{}.Mixin()
	reactionMixinFields0 := reactionMixin[0].Fields()
	_ = reactionMixinFields0
	reactionFields := schema.Reaction{}.Fields()
	_ = reactionFields
	// reactionDescCreatedAt is the schema descriptor for created_at field.
	reactionDescCreatedAt := reactionMixinFields0[0].Descriptor()
	// reaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	reaction.DefaultCreatedAt = reactionDescCreatedAt.Default.(func() time.Time)
	// reactionDescUpdatedAt is the schema descriptor for updated_at field.
	reactionDescUpdatedAt := reactionMixinFields0[1].Descriptor()
	// reaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	reaction.DefaultUpdatedAt = reactionDescUpdatedAt.Default.(func() time.Time)
	// reaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	reaction.UpdateDefaultUpdatedAt = reactionDescUpdatedAt.UpdateDefault.(func() time.Time)
	reactiontemplateMixin := schema.ReactionTemplate{}.Mixin()
	reactiontemplateMixinFields0 := reactiontemplateMixin[0].Fields()
	_ = reactiontemplateMixinFields0
	reactiontemplateFields := schema.ReactionTemplate{}.Fields()
	_ = reactiontemplateFields
	// reactiontemplateDescCreatedAt is the schema descriptor for created_at field.
	reactiontemplateDescCreatedAt := reactiontemplateMixinFields0[0].Descriptor()
	// reactiontemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	reactiontemplate.DefaultCreatedAt = reactiontemplateDescCreatedAt.Default.(func() time.Time)
	// reactiontemplateDescUpdatedAt is the schema descriptor for updated_at field.
	reactiontemplateDescUpdatedAt := reactiontemplateMixinFields0[1].Descriptor()
	// reactiontemplate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	reactiontemplate.DefaultUpdatedAt = reactiontemplateDescUpdatedAt.Default.(func() time.Time)
	// reactiontemplate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	reactiontemplate.UpdateDefaultUpdatedAt = reactiontemplateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// reactiontemplateDescReaction is the schema descriptor for reaction field.
	reactiontemplateDescReaction := reactiontemplateFields[0].Descriptor()
	// reactiontemplate.ReactionValidator is a validator for the "reaction" field. It is called by the builders before save.
	reactiontemplate.ReactionValidator = reactiontemplateDescReaction.Validators[0].(func(string) error)
	voteMixin := schema.Vote{}.Mixin()
	voteMixinFields0 := voteMixin[0].Fields()
	_ = voteMixinFields0
	voteMixinFields1 := voteMixin[1].Fields()
	_ = voteMixinFields1
	voteFields := schema.Vote{}.Fields()
	_ = voteFields
	// voteDescCreatedAt is the schema descriptor for created_at field.
	voteDescCreatedAt := voteMixinFields0[0].Descriptor()
	// vote.DefaultCreatedAt holds the default value on creation for the created_at field.
	vote.DefaultCreatedAt = voteDescCreatedAt.Default.(func() time.Time)
	// voteDescUpdatedAt is the schema descriptor for updated_at field.
	voteDescUpdatedAt := voteMixinFields0[1].Descriptor()
	// vote.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vote.DefaultUpdatedAt = voteDescUpdatedAt.Default.(func() time.Time)
	// vote.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vote.UpdateDefaultUpdatedAt = voteDescUpdatedAt.UpdateDefault.(func() time.Time)
	// voteDescIsDeleted is the schema descriptor for is_deleted field.
	voteDescIsDeleted := voteMixinFields1[0].Descriptor()
	// vote.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	vote.DefaultIsDeleted = voteDescIsDeleted.Default.(bool)
	votetemplateMixin := schema.VoteTemplate{}.Mixin()
	votetemplateMixinFields0 := votetemplateMixin[0].Fields()
	_ = votetemplateMixinFields0
	votetemplateFields := schema.VoteTemplate{}.Fields()
	_ = votetemplateFields
	// votetemplateDescCreatedAt is the schema descriptor for created_at field.
	votetemplateDescCreatedAt := votetemplateMixinFields0[0].Descriptor()
	// votetemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	votetemplate.DefaultCreatedAt = votetemplateDescCreatedAt.Default.(func() time.Time)
	// votetemplateDescUpdatedAt is the schema descriptor for updated_at field.
	votetemplateDescUpdatedAt := votetemplateMixinFields0[1].Descriptor()
	// votetemplate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	votetemplate.DefaultUpdatedAt = votetemplateDescUpdatedAt.Default.(func() time.Time)
	// votetemplate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	votetemplate.UpdateDefaultUpdatedAt = votetemplateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// votetemplateDescAnswer is the schema descriptor for answer field.
	votetemplateDescAnswer := votetemplateFields[0].Descriptor()
	// votetemplate.AnswerValidator is a validator for the "answer" field. It is called by the builders before save.
	votetemplate.AnswerValidator = votetemplateDescAnswer.Validators[0].(func(string) error)
}
