// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/poll"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/votetemplate"
)

// VoteTemplateCreate is the builder for creating a VoteTemplate entity.
type VoteTemplateCreate struct {
	config
	mutation *VoteTemplateMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (vtc *VoteTemplateCreate) SetCreatedAt(t time.Time) *VoteTemplateCreate {
	vtc.mutation.SetCreatedAt(t)
	return vtc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (vtc *VoteTemplateCreate) SetNillableCreatedAt(t *time.Time) *VoteTemplateCreate {
	if t != nil {
		vtc.SetCreatedAt(*t)
	}
	return vtc
}

// SetUpdatedAt sets the "updated_at" field.
func (vtc *VoteTemplateCreate) SetUpdatedAt(t time.Time) *VoteTemplateCreate {
	vtc.mutation.SetUpdatedAt(t)
	return vtc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (vtc *VoteTemplateCreate) SetNillableUpdatedAt(t *time.Time) *VoteTemplateCreate {
	if t != nil {
		vtc.SetUpdatedAt(*t)
	}
	return vtc
}

// SetAnswer sets the "answer" field.
func (vtc *VoteTemplateCreate) SetAnswer(s string) *VoteTemplateCreate {
	vtc.mutation.SetAnswer(s)
	return vtc
}

// SetPollID sets the "poll" edge to the Poll entity by ID.
func (vtc *VoteTemplateCreate) SetPollID(id int) *VoteTemplateCreate {
	vtc.mutation.SetPollID(id)
	return vtc
}

// SetNillablePollID sets the "poll" edge to the Poll entity by ID if the given value is not nil.
func (vtc *VoteTemplateCreate) SetNillablePollID(id *int) *VoteTemplateCreate {
	if id != nil {
		vtc = vtc.SetPollID(*id)
	}
	return vtc
}

// SetPoll sets the "poll" edge to the Poll entity.
func (vtc *VoteTemplateCreate) SetPoll(p *Poll) *VoteTemplateCreate {
	return vtc.SetPollID(p.ID)
}

// Mutation returns the VoteTemplateMutation object of the builder.
func (vtc *VoteTemplateCreate) Mutation() *VoteTemplateMutation {
	return vtc.mutation
}

// Save creates the VoteTemplate in the database.
func (vtc *VoteTemplateCreate) Save(ctx context.Context) (*VoteTemplate, error) {
	var (
		err  error
		node *VoteTemplate
	)
	vtc.defaults()
	if len(vtc.hooks) == 0 {
		if err = vtc.check(); err != nil {
			return nil, err
		}
		node, err = vtc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VoteTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = vtc.check(); err != nil {
				return nil, err
			}
			vtc.mutation = mutation
			if node, err = vtc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(vtc.hooks) - 1; i >= 0; i-- {
			if vtc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vtc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, vtc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*VoteTemplate)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from VoteTemplateMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (vtc *VoteTemplateCreate) SaveX(ctx context.Context) *VoteTemplate {
	v, err := vtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vtc *VoteTemplateCreate) Exec(ctx context.Context) error {
	_, err := vtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vtc *VoteTemplateCreate) ExecX(ctx context.Context) {
	if err := vtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vtc *VoteTemplateCreate) defaults() {
	if _, ok := vtc.mutation.CreatedAt(); !ok {
		v := votetemplate.DefaultCreatedAt()
		vtc.mutation.SetCreatedAt(v)
	}
	if _, ok := vtc.mutation.UpdatedAt(); !ok {
		v := votetemplate.DefaultUpdatedAt()
		vtc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vtc *VoteTemplateCreate) check() error {
	if _, ok := vtc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VoteTemplate.created_at"`)}
	}
	if _, ok := vtc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VoteTemplate.updated_at"`)}
	}
	if _, ok := vtc.mutation.Answer(); !ok {
		return &ValidationError{Name: "answer", err: errors.New(`ent: missing required field "VoteTemplate.answer"`)}
	}
	if v, ok := vtc.mutation.Answer(); ok {
		if err := votetemplate.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "VoteTemplate.answer": %w`, err)}
		}
	}
	return nil
}

func (vtc *VoteTemplateCreate) sqlSave(ctx context.Context) (*VoteTemplate, error) {
	_node, _spec := vtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (vtc *VoteTemplateCreate) createSpec() (*VoteTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &VoteTemplate{config: vtc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: votetemplate.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: votetemplate.FieldID,
			},
		}
	)
	if value, ok := vtc.mutation.CreatedAt(); ok {
		_spec.SetField(votetemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := vtc.mutation.UpdatedAt(); ok {
		_spec.SetField(votetemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := vtc.mutation.Answer(); ok {
		_spec.SetField(votetemplate.FieldAnswer, field.TypeString, value)
		_node.Answer = value
	}
	if nodes := vtc.mutation.PollIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   votetemplate.PollTable,
			Columns: []string{votetemplate.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: poll.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.poll_vote_templates = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VoteTemplateCreateBulk is the builder for creating many VoteTemplate entities in bulk.
type VoteTemplateCreateBulk struct {
	config
	builders []*VoteTemplateCreate
}

// Save creates the VoteTemplate entities in the database.
func (vtcb *VoteTemplateCreateBulk) Save(ctx context.Context) ([]*VoteTemplate, error) {
	specs := make([]*sqlgraph.CreateSpec, len(vtcb.builders))
	nodes := make([]*VoteTemplate, len(vtcb.builders))
	mutators := make([]Mutator, len(vtcb.builders))
	for i := range vtcb.builders {
		func(i int, root context.Context) {
			builder := vtcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VoteTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vtcb *VoteTemplateCreateBulk) SaveX(ctx context.Context) []*VoteTemplate {
	v, err := vtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vtcb *VoteTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := vtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vtcb *VoteTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := vtcb.Exec(ctx); err != nil {
		panic(err)
	}
}
