// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/poll"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/predicate"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/votetemplate"
)

// VoteTemplateQuery is the builder for querying VoteTemplate entities.
type VoteTemplateQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.VoteTemplate
	withPoll   *PollQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VoteTemplateQuery builder.
func (vtq *VoteTemplateQuery) Where(ps ...predicate.VoteTemplate) *VoteTemplateQuery {
	vtq.predicates = append(vtq.predicates, ps...)
	return vtq
}

// Limit adds a limit step to the query.
func (vtq *VoteTemplateQuery) Limit(limit int) *VoteTemplateQuery {
	vtq.limit = &limit
	return vtq
}

// Offset adds an offset step to the query.
func (vtq *VoteTemplateQuery) Offset(offset int) *VoteTemplateQuery {
	vtq.offset = &offset
	return vtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vtq *VoteTemplateQuery) Unique(unique bool) *VoteTemplateQuery {
	vtq.unique = &unique
	return vtq
}

// Order adds an order step to the query.
func (vtq *VoteTemplateQuery) Order(o ...OrderFunc) *VoteTemplateQuery {
	vtq.order = append(vtq.order, o...)
	return vtq
}

// QueryPoll chains the current query on the "poll" edge.
func (vtq *VoteTemplateQuery) QueryPoll() *PollQuery {
	query := &PollQuery{config: vtq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(votetemplate.Table, votetemplate.FieldID, selector),
			sqlgraph.To(poll.Table, poll.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, votetemplate.PollTable, votetemplate.PollColumn),
		)
		fromU = sqlgraph.SetNeighbors(vtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VoteTemplate entity from the query.
// Returns a *NotFoundError when no VoteTemplate was found.
func (vtq *VoteTemplateQuery) First(ctx context.Context) (*VoteTemplate, error) {
	nodes, err := vtq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{votetemplate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vtq *VoteTemplateQuery) FirstX(ctx context.Context) *VoteTemplate {
	node, err := vtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VoteTemplate ID from the query.
// Returns a *NotFoundError when no VoteTemplate ID was found.
func (vtq *VoteTemplateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vtq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{votetemplate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vtq *VoteTemplateQuery) FirstIDX(ctx context.Context) int {
	id, err := vtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VoteTemplate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VoteTemplate entity is found.
// Returns a *NotFoundError when no VoteTemplate entities are found.
func (vtq *VoteTemplateQuery) Only(ctx context.Context) (*VoteTemplate, error) {
	nodes, err := vtq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{votetemplate.Label}
	default:
		return nil, &NotSingularError{votetemplate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vtq *VoteTemplateQuery) OnlyX(ctx context.Context) *VoteTemplate {
	node, err := vtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VoteTemplate ID in the query.
// Returns a *NotSingularError when more than one VoteTemplate ID is found.
// Returns a *NotFoundError when no entities are found.
func (vtq *VoteTemplateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vtq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{votetemplate.Label}
	default:
		err = &NotSingularError{votetemplate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vtq *VoteTemplateQuery) OnlyIDX(ctx context.Context) int {
	id, err := vtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VoteTemplates.
func (vtq *VoteTemplateQuery) All(ctx context.Context) ([]*VoteTemplate, error) {
	if err := vtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return vtq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (vtq *VoteTemplateQuery) AllX(ctx context.Context) []*VoteTemplate {
	nodes, err := vtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VoteTemplate IDs.
func (vtq *VoteTemplateQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := vtq.Select(votetemplate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vtq *VoteTemplateQuery) IDsX(ctx context.Context) []int {
	ids, err := vtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vtq *VoteTemplateQuery) Count(ctx context.Context) (int, error) {
	if err := vtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return vtq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (vtq *VoteTemplateQuery) CountX(ctx context.Context) int {
	count, err := vtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vtq *VoteTemplateQuery) Exist(ctx context.Context) (bool, error) {
	if err := vtq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return vtq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (vtq *VoteTemplateQuery) ExistX(ctx context.Context) bool {
	exist, err := vtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VoteTemplateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vtq *VoteTemplateQuery) Clone() *VoteTemplateQuery {
	if vtq == nil {
		return nil
	}
	return &VoteTemplateQuery{
		config:     vtq.config,
		limit:      vtq.limit,
		offset:     vtq.offset,
		order:      append([]OrderFunc{}, vtq.order...),
		predicates: append([]predicate.VoteTemplate{}, vtq.predicates...),
		withPoll:   vtq.withPoll.Clone(),
		// clone intermediate query.
		sql:    vtq.sql.Clone(),
		path:   vtq.path,
		unique: vtq.unique,
	}
}

// WithPoll tells the query-builder to eager-load the nodes that are connected to
// the "poll" edge. The optional arguments are used to configure the query builder of the edge.
func (vtq *VoteTemplateQuery) WithPoll(opts ...func(*PollQuery)) *VoteTemplateQuery {
	query := &PollQuery{config: vtq.config}
	for _, opt := range opts {
		opt(query)
	}
	vtq.withPoll = query
	return vtq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VoteTemplate.Query().
//		GroupBy(votetemplate.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vtq *VoteTemplateQuery) GroupBy(field string, fields ...string) *VoteTemplateGroupBy {
	grbuild := &VoteTemplateGroupBy{config: vtq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := vtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return vtq.sqlQuery(ctx), nil
	}
	grbuild.label = votetemplate.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.VoteTemplate.Query().
//		Select(votetemplate.FieldCreatedAt).
//		Scan(ctx, &v)
func (vtq *VoteTemplateQuery) Select(fields ...string) *VoteTemplateSelect {
	vtq.fields = append(vtq.fields, fields...)
	selbuild := &VoteTemplateSelect{VoteTemplateQuery: vtq}
	selbuild.label = votetemplate.Label
	selbuild.flds, selbuild.scan = &vtq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a VoteTemplateSelect configured with the given aggregations.
func (vtq *VoteTemplateQuery) Aggregate(fns ...AggregateFunc) *VoteTemplateSelect {
	return vtq.Select().Aggregate(fns...)
}

func (vtq *VoteTemplateQuery) prepareQuery(ctx context.Context) error {
	for _, f := range vtq.fields {
		if !votetemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vtq.path != nil {
		prev, err := vtq.path(ctx)
		if err != nil {
			return err
		}
		vtq.sql = prev
	}
	return nil
}

func (vtq *VoteTemplateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VoteTemplate, error) {
	var (
		nodes       = []*VoteTemplate{}
		withFKs     = vtq.withFKs
		_spec       = vtq.querySpec()
		loadedTypes = [1]bool{
			vtq.withPoll != nil,
		}
	)
	if vtq.withPoll != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, votetemplate.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VoteTemplate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VoteTemplate{config: vtq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vtq.withPoll; query != nil {
		if err := vtq.loadPoll(ctx, query, nodes, nil,
			func(n *VoteTemplate, e *Poll) { n.Edges.Poll = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vtq *VoteTemplateQuery) loadPoll(ctx context.Context, query *PollQuery, nodes []*VoteTemplate, init func(*VoteTemplate), assign func(*VoteTemplate, *Poll)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*VoteTemplate)
	for i := range nodes {
		if nodes[i].poll_vote_templates == nil {
			continue
		}
		fk := *nodes[i].poll_vote_templates
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(poll.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "poll_vote_templates" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (vtq *VoteTemplateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vtq.querySpec()
	_spec.Node.Columns = vtq.fields
	if len(vtq.fields) > 0 {
		_spec.Unique = vtq.unique != nil && *vtq.unique
	}
	return sqlgraph.CountNodes(ctx, vtq.driver, _spec)
}

func (vtq *VoteTemplateQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := vtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (vtq *VoteTemplateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   votetemplate.Table,
			Columns: votetemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: votetemplate.FieldID,
			},
		},
		From:   vtq.sql,
		Unique: true,
	}
	if unique := vtq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := vtq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, votetemplate.FieldID)
		for i := range fields {
			if fields[i] != votetemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vtq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vtq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vtq *VoteTemplateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vtq.driver.Dialect())
	t1 := builder.Table(votetemplate.Table)
	columns := vtq.fields
	if len(columns) == 0 {
		columns = votetemplate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vtq.sql != nil {
		selector = vtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vtq.unique != nil && *vtq.unique {
		selector.Distinct()
	}
	for _, p := range vtq.predicates {
		p(selector)
	}
	for _, p := range vtq.order {
		p(selector)
	}
	if offset := vtq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vtq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VoteTemplateGroupBy is the group-by builder for VoteTemplate entities.
type VoteTemplateGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vtgb *VoteTemplateGroupBy) Aggregate(fns ...AggregateFunc) *VoteTemplateGroupBy {
	vtgb.fns = append(vtgb.fns, fns...)
	return vtgb
}

// Scan applies the group-by query and scans the result into the given value.
func (vtgb *VoteTemplateGroupBy) Scan(ctx context.Context, v any) error {
	query, err := vtgb.path(ctx)
	if err != nil {
		return err
	}
	vtgb.sql = query
	return vtgb.sqlScan(ctx, v)
}

func (vtgb *VoteTemplateGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range vtgb.fields {
		if !votetemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := vtgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vtgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vtgb *VoteTemplateGroupBy) sqlQuery() *sql.Selector {
	selector := vtgb.sql.Select()
	aggregation := make([]string, 0, len(vtgb.fns))
	for _, fn := range vtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(vtgb.fields)+len(vtgb.fns))
		for _, f := range vtgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(vtgb.fields...)...)
}

// VoteTemplateSelect is the builder for selecting fields of VoteTemplate entities.
type VoteTemplateSelect struct {
	*VoteTemplateQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vts *VoteTemplateSelect) Aggregate(fns ...AggregateFunc) *VoteTemplateSelect {
	vts.fns = append(vts.fns, fns...)
	return vts
}

// Scan applies the selector query and scans the result into the given value.
func (vts *VoteTemplateSelect) Scan(ctx context.Context, v any) error {
	if err := vts.prepareQuery(ctx); err != nil {
		return err
	}
	vts.sql = vts.VoteTemplateQuery.sqlQuery(ctx)
	return vts.sqlScan(ctx, v)
}

func (vts *VoteTemplateSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(vts.fns))
	for _, fn := range vts.fns {
		aggregation = append(aggregation, fn(vts.sql))
	}
	switch n := len(*vts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		vts.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		vts.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := vts.sql.Query()
	if err := vts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
