// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/predicate"
	"github.com/zoomoid/vox-populi/backend/pkg/v1/data/ent/votetemplate"
)

// VoteTemplateDelete is the builder for deleting a VoteTemplate entity.
type VoteTemplateDelete struct {
	config
	hooks    []Hook
	mutation *VoteTemplateMutation
}

// Where appends a list predicates to the VoteTemplateDelete builder.
func (vtd *VoteTemplateDelete) Where(ps ...predicate.VoteTemplate) *VoteTemplateDelete {
	vtd.mutation.Where(ps...)
	return vtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vtd *VoteTemplateDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vtd.hooks) == 0 {
		affected, err = vtd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VoteTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vtd.mutation = mutation
			affected, err = vtd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vtd.hooks) - 1; i >= 0; i-- {
			if vtd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vtd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vtd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (vtd *VoteTemplateDelete) ExecX(ctx context.Context) int {
	n, err := vtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vtd *VoteTemplateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: votetemplate.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: votetemplate.FieldID,
			},
		},
	}
	if ps := vtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// VoteTemplateDeleteOne is the builder for deleting a single VoteTemplate entity.
type VoteTemplateDeleteOne struct {
	vtd *VoteTemplateDelete
}

// Exec executes the deletion query.
func (vtdo *VoteTemplateDeleteOne) Exec(ctx context.Context) error {
	n, err := vtdo.vtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{votetemplate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vtdo *VoteTemplateDeleteOne) ExecX(ctx context.Context) {
	vtdo.vtd.ExecX(ctx)
}
