// Code generated by ent, DO NOT EDIT.

package votetemplate

import (
	"time"
)

const (
	// Label holds the string label denoting the votetemplate type in the database.
	Label = "vote_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAnswer holds the string denoting the answer field in the database.
	FieldAnswer = "answer"
	// EdgePoll holds the string denoting the poll edge name in mutations.
	EdgePoll = "poll"
	// Table holds the table name of the votetemplate in the database.
	Table = "vote_templates"
	// PollTable is the table that holds the poll relation/edge.
	PollTable = "vote_templates"
	// PollInverseTable is the table name for the Poll entity.
	// It exists in this package in order to avoid circular dependency with the "poll" package.
	PollInverseTable = "polls"
	// PollColumn is the table column denoting the poll relation/edge.
	PollColumn = "poll_vote_templates"
)

// Columns holds all SQL columns for votetemplate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAnswer,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "vote_templates"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"poll_vote_templates",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// AnswerValidator is a validator for the "answer" field. It is called by the builders before save.
	AnswerValidator func(string) error
)
